=== TumoroteK/TumoroteK/tumorotek-install/src/assembly/localhost/mbio/mbioApi.dtd
<!ELEMENT mbioConfig (printers,labels)>
	<!ELEMENT printers (printer+)>
		<!ELEMENT printer (licence,ipAddress,port,queue)>
		<!ATTLIST printer id CDATA #REQUIRED>
			<!ELEMENT licence (#PCDATA)>
			<!ELEMENT ipAddress (#PCDATA)>
			<!ELEMENT port (#PCDATA)>
			<!ELEMENT queue (#PCDATA)>
	<!ELEMENT labels (label+)>
		<!ELEMENT label (zplTemplate,parameters)>
		<!ATTLIST label id CDATA #REQUIRED>
			<!ELEMENT zplTemplate (#PCDATA)>
			<!ELEMENT parameters (param+)>
				<!ELEMENT param (name,value)>
					<!ELEMENT name (#PCDATA)>
					<!ELEMENT value (#PCDATA)>

=== TumoroteK/TumoroteK/tumorotek-interface/src/test/resources/tomcat/conf/Catalina/localhost/mbio/mbioApi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mbioConfig PUBLIC "-//Modul-Bio//DTD API Configuration 1.0//EN"
"mbioApi.dtd">

<!-- ===================================================================== -->
<!--                                                                       -->
<!--  Configuration  file  for MBioAPI                                     -->
<!--                                                                       -->
<!-- ===================================================================== -->

<mbioConfig>
	<printers>
		<printer id="1">
			<!--<licence>6F354213DE9452FAE35626B552C92220170F2DE0</licence>-->
			<licence>0D5B2CF39C8DD160B95F9A00CC075C330B7A7195</licence>
			<ipAddress>10.181.198.229</ipAddress>
			<!-- <port>515</port> -->
			<port>9100</port>
			<queue>raw</queue>
		</printer>
	</printers>
	<labels>
		<label id="1">
			<zplTemplate>standard.zpl</zplTemplate>
			<parameters>
				<param>
					<name>1</name>
					<value>1</value>
				</param>
				<param>
					<name>2</name>
					<value>2</value>
				</param>
				<param>
					<name>3</name>
					<value>3</value>
				</param>
				<param>
					<name>4</name>
					<value>4</value>
				</param>
				<param>
					<name>5</name>
					<value>5</value>
				</param>
				<param>
					<name>6</name>
					<value>6</value>
				</param>
			</parameters>
		</label>
	</labels>
</mbioConfig>
